lang: vi-VN
timezone: Asia/Ho_Chi_Minh

title: Kinh Sách
tagline: Kinh Sách Miễn Phí
email: itvtbadboy@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Kinh sách miễn phí giúp cộng đồng đọc kinh nghe pháp tiếp thu trí tuệ giữ vững lòng tin sống đời Chánh Đạo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kinhsach.github.io"
github_username: kinhsach

# Build settings
theme: jekyll-theme-chirpy
theme_mode: dark
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  facebook: # fill in your Facebook verification code

cdn: "https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/oracle"
avatar: "https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/oracle/kinh/cover-512.jpg"
social_preview_image: "https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/oracle/kinh/cover.jpg"
