# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: ko # 언어를 한국어로 설정

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Seoul # 서울 표준시로 설정

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: sumin lee # 블로그 제목 설정
tagline: archive # 부가 설명 설정

description: >- # SEO를 위한 설명 (키워드)
  Data Analytics, Automation, Sabermetrics

# Fill in the protocol & hostname for your site.
# E.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://ltnalsxl.github.io" # GitHub Pages URL

navigation:
  - text: "Home"
    url: "/"
  - text: "Categories"
    url: "/categories/"
    sublinks:
      - title: "📈 Data"
        url: "/categories/data/"
      - title: "🔧 Productivity Tools"
        url: "/categories/productivity-tools/"
      - title: "⚾ Sports"
        url: "/categories/sports/"
  - text: "Tags"
    url: "/tags/"
  - text: "Archives"
    url: "/archives/"
  - text: "About"
    url: "/about/"



github:
  username: ltnalsxl # GitHub 사용자명

twitter:
  username: # 트위터 계정이 없다면 비워둡니다

social:
  name: Sumin Lee
  email: fltnadls1011@gmail.com
  links:
    - https://github.com/ltnalsxl # GitHub 링크
    - https://www.linkedin.com/in/your-linkedin-id # LinkedIn 링크
    # 필요 시 다른 소셜 미디어 링크 추가 가능

    # 필요 시 다른 소셜 미디어 링크 추가 가능

# Site Verification Settings
webmaster_verifications:
  google: # 구글 인증 코드
  bing: # 빙 인증 코드
  alexa: # 알렉사 인증 코드
  yandex: # 얀덱스 인증 코드
  baidu: # 바이두 인증 코드
  facebook: # 페이스북 인증 코드

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: # Google Analytics ID
  goatcounter:
    id: # GoatCounter ID
  umami:
    id: # Umami ID
    domain: # Umami 도메인
  matomo:
    id: # Matomo ID
    domain: # Matomo 도메인
  cloudflare:
    id: # Cloudflare Web Analytics 토큰
  fathom:
    id: # Fathom Site ID

# Page views settings
pageviews:
  provider: # 현재는 'goatcounter'만 지원

# 테마 모드 설정
theme_mode: light # light 또는 dark 모드 설정 가능

# CDN 설정
cdn: "https://chirpy-img.netlify.app"

# 아바타 이미지 설정
avatar: "/assets/img/avatar.jpg" # 깃헙 프로필 이미지 업로드 경로 (로컬 파일을 사용하거나 URL로 설정 가능)

# SEO를 위한 소셜 미리보기 이미지 설정
social_preview_image: # SEO `og:image` 메타 태그용 사이트 전역 이미지 URL

# 포스트의 목차 표시 설정
toc: true # 글의 우측에 목차 표시

# 댓글 시스템 설정 (사용하지 않을 경우 비워둡니다)
comments:
  provider: # [disqus | utterances | giscus]
  disqus:
    shortname: # Disqus shortname 입력
  utterances:
    repo: # <gh-username>/<repo> 설정
  giscus:
    repo: # <gh-username>/<repo> 설정
    repo_id: 
    category: 
    category_id:
    mapping: # 기본값은 'pathname'
    lang: ko # 언어 설정 (기본값: 사이트 lang 값)

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, self-host 사용 여부 설정
    env: # 환경 설정 (development | production)

# PWA 설정 (Progressive Web App)
pwa:
  enabled: true # PWA 기능 사용
  cache:
    enabled: true # PWA 오프라인 캐시 사용

paginate: 10 # 한 페이지에 표시할 포스트 수

# The base URL of your site
baseurl: "" # 기본 URL 설정

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
