# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

<<<<<<< HEAD
# Only if your site type is GitHub Project sites and doesn't have a custom domain,
# change below value to '/projectname'.
baseurl: ''
=======
# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl: ""
>>>>>>> 1a148b47672b35d180699fc905d033785c8bbe28

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: America/New_York

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

<<<<<<< HEAD
title: Grace                          # the main title

tagline: 2021 Sep 24 updated   # it will display as the sub-title

description: >-                        # used by seo meta and the atom feed
=======
title: Grace # the main title

tagline: 2023 Mar 14 updated   # it will display as the sub-title

description: >- # used by seo meta and the atom feed
>>>>>>> 1a148b47672b35d180699fc905d033785c8bbe28
  A webpages focus on IT learning path.

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: 'https://ocholuo.github.io/'

github:
<<<<<<< HEAD
  username: ocholuo             # change to your github username

twitter:
  username: twitter_username            # change to your twitter username
=======
  username: ocholuo # change to your github username

twitter:
  username: twitter_username # change to your twitter username
>>>>>>> 1a148b47672b35d180699fc905d033785c8bbe28

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Grace JyL
<<<<<<< HEAD
  # email: example@doamin.com             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    # - https://twitter.com/username      # change to your twitter homepage
    - https://github.com/ocholuo       # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    - https://www.linkedin.com/in/grace-jy-l-0aaa32a1/

google_site_verification: google_meta_tag_verification # change to your verification string

# ↑ --------------------------


google_analytics:
  id: 'UA-179830187-1'              # fill in your Google Analytics ID
  # Google Analytics pageviews report settings
  pv:
    # fill in the Google Analytics superProxy endpoint of Google App Engine
    proxy_endpoint: 'https://myochosite-291718.appspot.com/query?id=ahNwfm15b2Nob3NpdGUtMjkxNzE4chULEghBcGlRdWVyeRiAgIDo14eBCgw'
    cache_path:       # the local PV cache data, friendly to visitors from GFW region
=======
  # email: example@domain.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    # - https://twitter.com/username # change to your twitter homepage
    - https://github.com/ocholuo  # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

google_site_verification: # fill in to your verification string

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

google_analytics:
  id: 'UA-179830187-1' # fill in your Google Analytics ID
  # Google Analytics pageviews report settings
  pv:
    # fill in the Google Analytics superProxy endpoint of Google App Engine
    proxy_endpoint: 'https://myochosite-291718.ue.r.appspot.com/query?id=ahNwfm15b2Nob3NpdGUtMjkxNzE4chULEghBcGlRdWVyeRiAgIDYmr-ACgw'
    cache_path: # the local PV cache data, friendly to visitors from GFW region
>>>>>>> 1a148b47672b35d180699fc905d033785c8bbe28

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
<<<<<<< HEAD
theme_mode: dark  # [light|dark]
=======
theme_mode: dark # [light|dark]
>>>>>>> 1a148b47672b35d180699fc905d033785c8bbe28

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
<<<<<<< HEAD
img_cdn: ''

# the avatar on sidebar, support local or CORS resources
avatar: /assets/img/huoye.jpg
=======
# img_cdn: 'https://chirpy-img.netlify.app'
img_cdn:

# the avatar on sidebar, support local or CORS resources
avatar: '/assets/img/huoye.jpg'
>>>>>>> 1a148b47672b35d180699fc905d033785c8bbe28

# boolean type, the global switch for ToC in posts.
toc: true

<<<<<<< HEAD
disqus:
  comments: true  # boolean type, the global switch for posts comments.
  shortname: 'https-ocholuo-github-io'    # Fill with your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
=======
comments:
  active: 'disqus' # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname: https-ocholuo-github-io # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # optional, default to 'pathname'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development|production]

pwa:
  enabled: true # the option for PWA feature
>>>>>>> 1a148b47672b35d180699fc905d033785c8bbe28

paginate: 15

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
<<<<<<< HEAD
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
=======
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
>>>>>>> 1a148b47672b35d180699fc905d033785c8bbe28
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

<<<<<<< HEAD

defaults:
  -
    scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true    # Hide title in mobile screens.
=======
defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: true
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true
>>>>>>> 1a148b47672b35d180699fc905d033785c8bbe28

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
<<<<<<< HEAD
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - '*.json'
=======
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - node_modules
  - package*.json
>>>>>>> 1a148b47672b35d180699fc905d033785c8bbe28

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
