# Site Configuration

theme: jekyll-theme-chirpy

lang: ko
timezone: Asia/Seoul

title: "우진의 Sec&Tech 블로그"
tagline: "보안, 포렌식, 자동화, 개발 인사이트"
description: >
  실전 보안, 디지털 포렌식, 보안 자동화, 클라우드, 개발 등 IT 테크닉 & 경험을 아카이브합니다.

url: "https://leewoojin.github.io"

github:
  username: woojind03  # 본인 깃허브 ID

twitter:
  username: ""  # 사용 안하면 비워둠

social:
  name: 이우진
  email: your_email@example.com # 본인 이메일로 변경
  links:
    - https://github.com/woojin03
    # 필요 시 추가
    # - https://www.linkedin.com/in/woojin03

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

analytics:
  google:
    id: # 추후 Google Analytics ID 넣기

pageviews:
  provider:

theme_mode: # 비워두면 시스템 자동, "dark" 강제 가능

cdn: "" # 직접 CDN 미사용이면 비워둠

avatar: "/commons/avatar.jpg" # 본인 프로필 이미지 파일 경로(assets/commons/avatar.jpg 업로드 필요)

social_preview_image: # (선택) 대표 미리보기 이미지 경로

toc: true

comments:
  provider: # [disqus | utterances | giscus]
  # 예시: utterances
  # utterances:
  #   repo: woojind03/leewoojin.github.io
  #   issue_term: pathname

assets:
  self_host:
    enabled:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10

baseurl: "" # 루트 도메인일 때 비움

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
