

# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'


# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    - targets: ['localhost:9090']
      labels:
        group: "prometheus"

  - job_name: "go-test"
    scrape_interval: 60s
    scrape_timeout: 60s
    static_configs:
    # - targets: ["localhost:8888"]
    - targets: ["192.168.0.226:8888"]

  - job_name: "go-client"
    static_configs:
    - targets: ["192.168.0.226:8090"]

  - job_name: "example-random"
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ["192.168.0.226:8080", "192.168.0.226:8081"]
        labels:
          group: "production"
      - targets: ["192.168.0.226:8082"]
        labels:
          group: "canary"
      - targets: ["localhost:8083"]
        labels:
          group: "canary"


  - job_name: hpa-sim
    scrape_interval: 10s
    kubernetes_sd_configs:
      - role: pod
    static_configs:
      - targets:
        - "hpa-sim.default:80"
    relabel_configs:

      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: hpa-sim

      - source_labels: [__address__]
        action: replace
        target_label: __address__
        regex: ([^:]+)(?::\d+)?
        replacement: ${1}:8080

      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: k8s_namespace

      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: k8s_pod_name


# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
