name: CI

on:
  push:
    branches:
      - master
      - "hotfix/*"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - .gitignore
      - "docs/**"
      - README.md
      - LICENSE
  pull_request:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - .gitignore
      - "docs/**"
      - README.md
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["3.1", "3.2", "3.3"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for posts's lastmod

      # Ruby 수동 설치
      - name: Install Ruby ${{ matrix.ruby }}
        run: |
          RUBY_VERSION=${{ matrix.ruby }}
          INSTALL_PATH=/opt/hostedtoolcache/Ruby/${RUBY_VERSION}/x64

          sudo mkdir -p $INSTALL_PATH
          sudo chown -R $(whoami) $INSTALL_PATH

          # ruby-build 설치 및 Ruby 빌드
          curl -fsSL https://github.com/rbenv/ruby-build/archive/refs/heads/master.tar.gz | tar xz
          cd ruby-build-* && sudo ./install.sh
          ruby-build $RUBY_VERSION $INSTALL_PATH
          touch $INSTALL_PATH.complete

          # PATH 설정
          echo "PATH=$INSTALL_PATH/bin:$PATH" >> $GITHUB_ENV

      - name: Verify Ruby Version
        run: |
          ruby --version

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Build Assets
        run: npm i && npm run build

      - name: Test Site
        run: bash tools/test.sh