name: CI

on:
  push:
    branches:
      - master
      - "hotfix/*"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - .gitignore
      - "docs/**"
      - README.md
      - LICENSE
  pull_request:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - .gitignore
      - "docs/**"
      - README.md
      - LICENSE


jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        ruby: ["3.1", "3.2", "3.3"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev zlib1g-dev libreadline-dev \
            libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev \
            libffi-dev git

      - name: Install ruby-build
        run: |
          git clone https://github.com/rbenv/ruby-build.git
          cd ruby-build
          sudo ./install.sh

      - name: Install Ruby ${{ matrix.ruby }}
        run: |
          RUBY_VERSION=${{ matrix.ruby }}
          INSTALL_PATH=/opt/hostedtoolcache/Ruby/${RUBY_VERSION}/x64

          sudo mkdir -p $INSTALL_PATH
          sudo chown -R $(whoami) $INSTALL_PATH

          ruby-build $RUBY_VERSION $INSTALL_PATH
          touch $INSTALL_PATH.complete

          echo "PATH=$INSTALL_PATH/bin:$PATH" >> $GITHUB_ENV

      - name: Verify Ruby Version
        run: |
          ruby --version
          gem --version

      - name: Install Bundler
        run: |
          gem install bundler
          bundle install

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Build Assets
        run: npm install && npm run build

      - name: Test Site
        run: bash tools/test.sh