name: 'grace-project-image-builder'
on:
  workflow_run:
    workflows: ['Run Tests']
    branches: [main]
    types:
      - completed
  # push:
  #   branches:
  #     - master
  #   paths-ignore:
  #     - .gitignore
  #     - README.md
  #     - LICENSE
  schedule:
    - cron: '0 21 * * *'

jobs:
  run_project_webscrap_apt_img_builder:
    name: project webscrap_apt print img
    # runs-on: macOS-latest
    runs-on: ubuntu-latest

    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          PROJECT_NAME: webscrap_apt
        run: |
          echo $MY_VAR $PROJECT_NAME.

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # for posts's lastmod

      - name: Install Python dependencies
        run: python -m pip install -r ./_posts/00CodeNote/project/webscrap_apt/requirements.txt

      - name: run img player
        run: python ./_posts/00CodeNote/project/webscrap_apt/img_play.py

      - name: Commit and push changes
        run: |
          git config --global user.name "grace"
          git config --global user.email "lgraceye@hotmail.com"
          git pull origin master
          git add .
          git commit -m "Auto updating csv to repo"
          git push
