name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ] # or 'main' depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Match your local version
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Chirpy requires Node.js

      - name: Install dependencies
        run: |
          npm install
          bundle install

      - name: Build assets
        run: npm run build

      - name: Build site
        run: bundle exec jekyll build --baseurl "${{ github.event.repository.name }}"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages # The branch GitHub Pages uses